
os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9
script:
  # Committing packages to get files into pods/carthage. Need this to test
  - rm -rf Packages/
  - eval "$(curl -sL https://swift.vapor.sh/ci)"
